## NumPy Arrays

### Manipulate Array

In [147]:
import numpy as np

arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [148]:
ranarr = np.random.randint(0, 50, 20)
ranarr

array([29, 24, 44,  5, 40,  9, 17, 12, 16, 35, 13, 47, 16, 47, 37, 26, 47,
       18, 33, 40])

In [149]:
arr.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [150]:
ranarr = ranarr.reshape(4, 5)

In [151]:
ranarr.max()

47

In [152]:
print(ranarr.min())
ranarr.argmin() # get the index of min value

5


3

In [153]:
ranarr.mean()

27.75

In [154]:
ranarr.shape

(4, 5)

In [155]:
ranarr = ranarr.reshape(5, 4)
ranarr.shape

(5, 4)

In [156]:
ranarr.dtype

dtype('int32')

In [159]:
from numpy.random import randint
randint(1, 32)

8