## NumPy Arrays

### Generate Array

In [1]:
numbers = list(range(10))
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
# Convert list to numpy array
import numpy as np
arr = np.array(numbers)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# The number of columns MUST be same
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1, 10, 2) # 2 is step size

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# Create array with evenly distributed numbers
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [20]:
np.eye(4) # Identity metrics

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.59154591, 0.73349578, 0.95873229, 0.66562315, 0.43113326])

In [24]:
np.random.rand(2, 3)

array([[0.80901994, 0.45863641, 0.24544114],
       [0.24312759, 0.3329844 , 0.14810878]])

In [26]:
np.random.randn(2, 3)

array([[-0.13209163,  1.10233555,  1.48589565],
       [-0.28251424,  1.06501635,  0.02618761]])

In [30]:
np.random.randint(1, 100, 4) # Get random number between 1 and 100 (exclusive)

array([96, 96, 48, 44])