## Indexing

- Works similar to list/array

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[1]

1

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[3:] # slicing to take index 3 and beyond

array([3, 4, 5, 6, 7, 8, 9])

In [6]:
arr_copy = arr.copy() # deep clone
arr_copy[:] = 100 # assign 100 to each index
print (arr)
arr_copy

[0 1 2 3 4 5 6 7 8 9]


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

## Selection

In [10]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print(arr_2d[0][1])
print(arr_2d[0,1]) # numpy array supports this syntax

2
2


In [15]:
arr_2d[1:,0:2] # slicing multi-dimensional array

array([[4, 5],
       [7, 8]])

In [22]:
arr_with_gt4 = arr_2d > 4 # apply condition to array values
arr_with_gt4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [23]:
arr_2d[arr_with_gt4] # converts to single dimension array

array([5, 6, 7, 8, 9])

In [25]:
arr_2d[arr_2d > 4] # combine condition and filter

array([5, 6, 7, 8, 9])

In [27]:
arr_2d = np.arange(30).reshape(5, 6)
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [29]:
arr_2d[1:3] # select rows

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [30]:
arr_2d[:, 1:4] # select columns

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])