## Numpy Operations

In [28]:
import numpy as np

In [29]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr + 2 # add 2 to each element

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
arr + arr # add elements of two arrays at same index

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [33]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [34]:
np.max(arr)

9

In [35]:
np.mean(arr)

4.5

In [36]:
arr_2d = arr.reshape(2, 5)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
arr_2d.sum(axis=0) # sum columns

array([ 5,  7,  9, 11, 13])

In [38]:
arr_2d.sum(axis=1) # sum rows

array([10, 35])